pool:
  vmImage: ubuntu-latest

steps:
  - task: CmdLine@2
    name: PackageDexter
    displayName: Package Dexter Microservice
    inputs:
      script: 'mvn spring-boot:build-image'
      workingDirectory: 'dexter/'
  - task: CmdLine@2
    name: PackageRidik
    displayName: Package Ridik Microservice
    inputs:
      script: 'mvn spring-boot:build-image'
      workingDirectory: 'ridik/'
  - task: CmdLine@2
    name: PackageJobbie
    displayName: Package Jobbie Microservice
    inputs:
      script: 'mvn spring-boot:build-image'
      workingDirectory: 'jobbie/'

  - task: CmdLine@2
    name: ExecuteE2E
    displayName: Execute E2E
    inputs:
      script: 'mvn test'
      workingDirectory: 'e2e/'
