# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Dexter Microservice Container Image
      run: mvn spring-boot:build-image
      working-directory: 'dexter/'
    - name: Build Ridik Microservice Container Image
      run: mvn spring-boot:build-image
      working-directory: 'ridik/'
    - name: Build Jobbie Microservice Container Image
      run: mvn spring-boot:build-image
      working-directory: 'jobbie/'
    - name: Execute End2End Test
      run: mvn test
      working-directory: 'e2e/'      
